(function($,api){var $window=$(window),$document=$(document),$body=$('body');wp.customize.bind('ready',function(){$('input[name=kadence-flush-local-fonts-button]').on('click',function(e){var data={wp_customize:'on',action:'kadence_flush_fonts_folder',nonce:kadenceCustomizerControlsData.flushFonts};$('input[name=kadence-flush-local-fonts-button]').attr('disabled','disabled');$.post(ajaxurl,data,function(response){if(response&&response.success){$('input[name=kadence-flush-local-fonts-button]').val('Successfully Flushed');}else{$('input[name=kadence-flush-local-fonts-button]').val('Failed, Reload Page and Try Again');}});});wp.customize.state.create('kadenceTab');wp.customize.state('kadenceTab').set('general');wp.customize.sectionConstructor['kadence_section_pro']=wp.customize.Section.extend({attachEvents:()=>{},isContextuallyActive:()=>{return true;}});$('#customize-theme-controls').on('click','.kadence-build-tabs-button:not(.kadence-nav-tabs-button)',function(e){e.preventDefault();wp.customize.previewedDevice.set($(this).attr('data-device'));});$('#customize-theme-controls').on('click','.kadence-compontent-tabs-button:not(.kadence-nav-tabs-button)',function(e){e.preventDefault();wp.customize.state('kadenceTab').set($(this).attr('data-tab'));});var setCustomTabElementsDisplay=function(){var tabState=wp.customize.state('kadenceTab').get(),$tabs=$('.kadence-compontent-tabs-button:not(.kadence-nav-tabs-button)');$tabs.removeClass('nav-tab-active').filter('.kadence-'+tabState+'-tab').addClass('nav-tab-active');}
wp.customize.state('kadenceTab').bind(setCustomTabElementsDisplay);$('#customize-theme-controls').on('click','customize-section-back',function(e){wp.customize.state('kadenceTab').set('general');});if(kadenceCustomizerControlsData&&kadenceCustomizerControlsData.contexts){_.each(kadenceCustomizerControlsData.contexts,function(rules,key){var getSetting=function(settingName){switch(settingName){case'__device':return wp.customize.previewedDevice;break;case'__current_tab':return wp.customize.state('kadenceTab');break;default:if(kadenceCustomizerControlsData.source){if(wp.customize(kadenceCustomizerControlsData.source+'['+settingName+']')){return wp.customize(kadenceCustomizerControlsData.source+'['+settingName+']');}else{return wp.customize(settingName);}}
return wp.customize(settingName);break;}}
var initContext=function(element){var isDisplayed=function(){var displayed=false,relation=rules['relation'];if('OR'!==relation){relation='AND';displayed=true;}
_.each(rules,function(rule,i){if('relation'==i)return;if('AND'==relation&&false==displayed)return;if(undefined===rule['setting'])return;var result=false,setting=getSetting(rule['setting']);if(undefined!==setting){var operator=rule['operator'],comparedValue=rule['value'],currentValue=setting.get();if(undefined==operator||'='==operator){operator='==';}
if('sub_object_contains'===operator){if(undefined!==currentValue[rule['sub_key']]){currentValue=currentValue[rule['sub_key']];}}
if('sub_object_does_not_contain'===operator){if(undefined!==currentValue[rule['sub_key']]){currentValue=currentValue[rule['sub_key']];}}
switch(operator){case'>':result=currentValue>comparedValue;break;case'<':result=currentValue<comparedValue;break;case'>=':result=currentValue>=comparedValue;break;case'<=':result=currentValue<=comparedValue;break;case'in':result=0<=comparedValue.indexOf(currentValue);break;case'not_in':result=0>comparedValue.indexOf(currentValue);break;case'contain':result=0<=currentValue.indexOf(comparedValue);break;case'not_contain':result=0>currentValue.indexOf(comparedValue);break;case'in':result=0<=comparedValue.indexOf(currentValue);break;case'array_includes':result=currentValue.includes(comparedValue);break;case'sub_object_does_not_contain':if(rule['responsive']){result=true;{Object.keys({'desktop':'','tablet':'','mobile':''}).map((device)=>{if(currentValue[device].includes(comparedValue)){result=false;}})}}else{result=!currentValue.includes(comparedValue);}
break;case'sub_object_contains':if(rule['responsive']){{Object.keys({'desktop':'','tablet':'','mobile':''}).map((device)=>{if(currentValue[device].includes(comparedValue)){result=true;}})}}else{result=currentValue.includes(comparedValue);}
break;case'empty':result=(currentValue===undefined||currentValue==null||currentValue.length<=0);break;case'!empty':result=typeof currentValue!=='undefined'&&undefined!==currentValue&&null!==currentValue&&''!==currentValue;break;case'!=':result=comparedValue!==currentValue;break;case'load_italic':result=false;if(currentValue['family']&&currentValue['google']&&currentValue['variant']){if(0>currentValue['variant'].indexOf('italic')){if(kadenceCustomizerControlsData.gfontvars&&kadenceCustomizerControlsData.gfontvars[currentValue['family']]&&kadenceCustomizerControlsData.gfontvars[currentValue['family']].v&&kadenceCustomizerControlsData.gfontvars[currentValue['family']].v.includes('italic')){result=true;}}}
break;default:result=comparedValue==currentValue;break;}}
switch(relation){case'OR':displayed=displayed||result;break;default:displayed=displayed&&result;break;}});return displayed;};var setActiveState=function(){element.active.set(isDisplayed());};_.each(rules,function(rule,i){if('relation'==i)return;var setting=getSetting(rule['setting']);if(undefined!==setting){setting.bind(setActiveState);}});element.active.validate=isDisplayed;setActiveState();};if(0==key.indexOf('kadence_customizer')){wp.customize.section(key,initContext);}else{wp.customize.control(key,initContext);}});}
var setCustomResponsiveElementsDisplay=function(){var device=wp.customize.previewedDevice.get(),$tabs=$('.kadence-build-tabs-button.nav-tab');$tabs.removeClass('nav-tab-active').filter('.preview-'+device).addClass('nav-tab-active');}
wp.customize.previewedDevice.bind(setCustomResponsiveElementsDisplay);wp.customize.section.each(function(section){section.expanded.bind(setCustomResponsiveElementsDisplay);});var resizePreviewer=function(){var $section=$('.control-section.kadence-builder-active');var $footer=$('.control-section.kadence-footer-builder-active');if($body.hasClass('kadence-builder-is-active')||$body.hasClass('kadence-footer-builder-is-active')){if($body.hasClass('kadence-footer-builder-is-active')&&0<$footer.length&&!$footer.hasClass('kadence-builder-hide')){setTimeout(function(){wp.customize.previewer.container.css('bottom',$footer.outerHeight()+'px');},250);}else if($body.hasClass('kadence-builder-is-active')&&0<$section.length&&!$section.hasClass('kadence-builder-hide')){setTimeout(function(){wp.customize.previewer.container.css({"bottom":$section.outerHeight()+'px'});},250);}else{wp.customize.previewer.container.css('bottom','');}}else{wp.customize.previewer.container.css('bottom','');}}
$window.on('resize',resizePreviewer);wp.customize.previewedDevice.bind(function(device){setTimeout(function(){resizePreviewer();},250);});var reloadPreviewer=function(){$(wp.customize.previewer.container).find('iframe').css('position','static');$(wp.customize.previewer.container).find('iframe').css('position','absolute');}
wp.customize.previewer.bind('ready',reloadPreviewer);var initHeaderBuilderPanel=function(panel){var section=wp.customize.section('kadence_customizer_header_builder');if(section){var $section=section.contentContainer,section_layout=wp.customize.section('kadence_customizer_header_layout');panel.expanded.bind(function(isExpanded){_.each(section.controls(),function(control){if('resolved'===control.deferred.embedded.state()){return;}
control.renderContent();control.deferred.embedded.resolve();control.container.trigger('init');});if(isExpanded){$body.addClass('kadence-builder-is-active');$section.addClass('kadence-builder-active');$section.css('display','none').height();$section.css('display','block');}else{$body.removeClass('kadence-builder-is-active');$section.removeClass('kadence-builder-active');}
_.each(section_layout.controls(),function(control){if('resolved'===control.deferred.embedded.state()){return;}
control.renderContent();control.deferred.embedded.resolve();control.container.trigger('init');});resizePreviewer();});$section.on('click','.kadence-builder-tab-toggle',function(e){e.preventDefault();$section.toggleClass('kadence-builder-hide');resizePreviewer();});}};wp.customize.panel('kadence_customizer_header',initHeaderBuilderPanel);var initFooterBuilderPanel=function(panel){var section=wp.customize.section('kadence_customizer_footer_builder');if(section){var $section=section.contentContainer,section_layout=wp.customize.section('kadence_customizer_footer_layout');panel.expanded.bind(function(isExpanded){_.each(section.controls(),function(control){if('resolved'===control.deferred.embedded.state()){return;}
control.renderContent();control.deferred.embedded.resolve();control.container.trigger('init');});if(isExpanded){$body.addClass('kadence-footer-builder-is-active');$section.addClass('kadence-footer-builder-active');$section.css('display','none').height();$section.css('display','block');}else{$body.removeClass('kadence-footer-builder-is-active');$section.removeClass('kadence-footer-builder-active');}
_.each(section_layout.controls(),function(control){if('resolved'===control.deferred.embedded.state()){return;}
control.renderContent();control.deferred.embedded.resolve();control.container.trigger('init');});resizePreviewer();});$section.on('click','.kadence-builder-tab-toggle',function(e){e.preventDefault();$section.toggleClass('kadence-builder-hide');resizePreviewer();});}};wp.customize.panel('kadence_customizer_footer',initFooterBuilderPanel);});})(jQuery,wp);