import{create}from'zustand';import*as rsssl_api from"../../utils/api";import{__}from"@wordpress/i18n";import{produce}from"immer";import React from"react";import{addUrlRef}from"../../utils/AddUrlRef";const UseRiskData=create((set,get)=>({dummyRiskData:[{id:'force_update',name:'Force Update',value:'l',description:__('Force update the plugin or theme','really-simple-ssl')},{id:'quarantine',name:'Quarantine',value:'m',description:__('Isolates the plugin or theme if no update can be performed','really-simple-ssl')},],riskData:[],riskLevels:{l:1,m:2,h:3,c:4,},vulnerabilities:[],processing:false,dataLoaded:false,updates:0,HighestRisk:false,lastChecked:'',vulEnabled:false,riskNaming:{},vulList:[],setDataLoaded:(value)=>set({dataLoaded:value}),updateRiskData:async(field,value)=>{if(get().processing)return;set({processing:true});set(produce((state)=>{let index=state.riskData.findIndex((item)=>item.id===field);state.riskData[index].value=value;state.riskData=get().enforceCascadingRiskLevels(state.riskData);}));try{await rsssl_api.doAction('vulnerabilities_measures_set',{riskData:get().riskData,});set({dataLoaded:true,processing:false});}catch(e){console.log(e);}
set({processing:false})},enforceCascadingRiskLevels:(data)=>{if(data.length===0)return data;let forceUpdateRiskLevel=data.filter((item)=>item.id==='force_update')[0].value;let quarantineRiskLevel=data.filter((item)=>item.id==='quarantine')[0].value;forceUpdateRiskLevel=get().riskLevels.hasOwnProperty(forceUpdateRiskLevel)?get().riskLevels[forceUpdateRiskLevel]:5;quarantineRiskLevel=get().riskLevels.hasOwnProperty(quarantineRiskLevel)?get().riskLevels[quarantineRiskLevel]:5;let quarantineIndex=data.findIndex((item)=>item.id==='quarantine');if(quarantineRiskLevel<forceUpdateRiskLevel){data[quarantineIndex].value=Object.keys(get().riskLevels).find(key=>get().riskLevels[key]===forceUpdateRiskLevel);}
if(forceUpdateRiskLevel===5){data[quarantineIndex].value='*';}
let disableUpTo=forceUpdateRiskLevel>0?forceUpdateRiskLevel:0
let disabledRiskLevels=Array.from(Array(disableUpTo).keys()).map(x=>x);disabledRiskLevels=disabledRiskLevels.map((level)=>{return Object.keys(get().riskLevels).find(key=>get().riskLevels[key]===level);});data[quarantineIndex].disabledRiskLevels=disabledRiskLevels;return data;},fetchFirstRun:async()=>{if(get().processing)return;set({processing:true});await rsssl_api.doAction('vulnerabilities_scan_files');set({processing:false});},fetchVulnerabilities:async()=>{if(get().processing)return;set({processing:true});let data={};try{const fetched=await rsssl_api.doAction('hardening_data',data);let vulList=[];let vulnerabilities=0;if(fetched.data.vulList){vulnerabilities=fetched.data.vulnerabilities;vulList=fetched.data.vulList;if(typeof vulList==='object'){vulList=Object.values(vulList);}
vulList.forEach(function(item,i){let updateUrl=item.update_available?rsssl_settings.plugins_url+"?plugin_status=upgrade":'#settings/vulnerabilities';item.vulnerability_action=<div className="rsssl-action-buttons"><a className="rsssl-button button-secondary"
href={addUrlRef("https://really-simple-ssl.com/vulnerability/"+item.rss_identifier)}
target={"_blank"}rel="noopener noreferrer">{__("Details","really-simple-ssl")}</a><a disabled={!item.update_available}href={updateUrl}
className="rsssl-button button-primary">{__("Update","really-simple-ssl")}</a></div>});}
let riskData=fetched.data.riskData;if(!Array.isArray(riskData)){riskData=[]}
riskData=get().enforceCascadingRiskLevels(riskData);set(produce((state)=>{state.vulnerabilities=vulnerabilities;state.vulList=vulList;state.updates=fetched.data.updates;state.dataLoaded=true;state.riskNaming=fetched.data.riskNaming;state.lastChecked=fetched.data.lastChecked;state.vulEnabled=fetched.data.vulEnabled;state.riskData=riskData;state.processing=false;}))}catch(e){console.error(e);}},vulnerabilityCount:()=>{let vuls=get().vulList;let vulsArray=[];Object.keys(vuls).forEach(function(key){vulsArray.push(vuls[key]);});let riskLevels=['c','h','m','l'];return riskLevels.map(function(level){return{level:level,count:vulsArray.filter(function(vul){return vul.risk_level===level;}).length};});},vulnerabilityScore:()=>{let score=0;let vulnerabilitiesList=get().vulList;Object.keys(vulnerabilitiesList).forEach(function(key){if(vulnerabilitiesList[key].risk_level==='c'){score=5;}else if(score<1){score=1;}});return score;},hardeningScore:()=>{let score=0;let vulnerabilitiesList=get().vulnerabilities;for(let i=0;i<vulnerabilitiesList.length;i++){score+=vulnerabilitiesList[i].hardening_score;}
return score;},activateVulnerabilityScanner:async()=>{try{const fetched=await rsssl_api.doAction('rsssl_scan_files');if(fetched.request_success){await get().fetchVulnerabilities();}}catch(e){console.error(e);}}}));export default UseRiskData;