import{create}from'zustand';import*as rsssl_api from"../../utils/api";import{produce}from"immer";const IpAddressDataTableStore=create((set,get)=>({processing:false,dataLoaded:false,ipAddress:'',highestIP:'',lowestIP:'',statusSelected:'blocked',inputRangeValidated:false,cidr:'',ip_count:'',canSetCidr:false,ipRange:{},idSelected:'',pagination:{},dataActions:{},IpDataTable:[],maskError:false,rowCleared:false,setMaskError:(maskError)=>{set({maskError});},fetchData:async(action,dataActions)=>{set({processing:true});set({dataLoaded:false});set({rowCleared:true});if(Object.keys(dataActions).length===0){return;}
try{const response=await rsssl_api.doAction(action,dataActions);if(response){set({IpDataTable:response,dataLoaded:true,processing:false,pagination:response.pagination});}}catch(e){console.log(e);}finally{set({processing:false});set({rowCleared:false});}},handleIpTableSearch:async(search,searchColumns)=>{set(produce((state)=>{state.dataActions={...state.dataActions,search,searchColumns};}));},handleIpTablePageChange:async(page,pageSize)=>{set(produce((state)=>{state.dataActions={...state.dataActions,page,pageSize};}));},handleIpTableRowsChange:async(currentRowsPerPage,currentPage)=>{set(produce((state)=>{state.dataActions={...state.dataActions,currentRowsPerPage,currentPage};}));},handleIpTableSort:async(column,sortDirection)=>{set(produce((state)=>{state.dataActions={...state.dataActions,sortColumn:column,sortDirection};}));},handleIpTableFilter:async(column,filterValue)=>{set(produce((state)=>{state.dataActions={...state.dataActions,filterColumn:column,filterValue};}));},setIpAddress:(ipAddress)=>{if(ipAddress.length===0){return;}
let ipRegex=/^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$|^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,4}|((25[0-5]|(2[0-4]|1{0,1}[0-9])?[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9])?[0-9]))|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9])?[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9])?[0-9]))$/;if(ipAddress.includes('/')){let finalIp='';let[ip,mask]=ipAddress.split('/');ip=ip.replace(/,/g,'.');if(mask.length<=0){if(!ipRegex.test(ip)){set({maskError:true});}else{set({maskError:false});}
finalIp=`${ip}/${mask}`;}else{finalIp=mask?`${ip}/${mask}`:ip;}
set({ipAddress:finalIp})}else{if(!ipRegex.test(ipAddress)){set({maskError:true});}else{set({maskError:false});}
set({ipAddress:ipAddress.replace(/,/g,'.')})}},resetRange:()=>{set({inputRangeValidated:false});set({highestIP:''});set({lowestIP:''});set({ipAddress:''});set({maskError:false});},setStatusSelected:(statusSelected)=>{set({statusSelected});},setId:(idSelected)=>{set({idSelected});},updateRow:async(value,status,dataActions)=>{set({processing:true});let data={value:value,status:status};try{const response=await rsssl_api.doAction('ip_update_row',data);if(response&&response.request_success){await get().fetchData('rsssl_limit_login',dataActions);return{success:true,message:response.message,response};}else{return{success:false,message:response?.message||'Failed to add ip',response};}}catch(e){return{success:false,message:'Error occurred',error:e};}finally{set({processing:false});}},validateIpv4:(ip)=>{const parts=ip.split(".");if(parts.length!==4)return false;for(let part of parts){const num=parseInt(part,10);if(isNaN(num)||num<0||num>255)return false;}
return true;},validateIpv6:(ip)=>{const parts=ip.split(":");if(parts.length!==8)return false;for(let part of parts){if(part.length>4||!/^[0-9a-fA-F]+$/.test(part))return false;}
return true;},extendIpV6:(ip)=>{if(ip==='::')ip='0::0';if(ip.includes('::')){const parts=ip.split('::');if(parts.length>2)return false;const left=parts[0].split(':').filter(Boolean);const right=parts[1].split(':').filter(Boolean);const zerosNeeded=8-(left.length+right.length);return[...left,...Array(zerosNeeded).fill('0'),...right].join(':');}
return ip;},ipToNumber:(ip)=>{if(get().validateIpv4(ip)){return get().ipV4ToNumber(ip);}else if(get().validateIpv6(get().extendIpV6(ip))){return get().ipV6ToNumber(get().extendIpV6(ip));}},ipV4ToNumber:(ip)=>{return ip.split(".").reduce((acc,cur)=>(acc*256+parseInt(cur,10))>>>0,0);},ipV6ToNumber:(ip)=>{return ip.split(":").reduce((acc,cur)=>{const segmentValue=parseInt(cur,16);if(isNaN(segmentValue)){console.warn(`Invalid segment in IPv6 address: ${oldIp}`);return acc;}
return(acc<<BigInt(16))+BigInt(segmentValue);},BigInt(0));},validateIpRange:(lowest,highest)=>{set({inputRangeValidated:false});let from='';let to='';if(lowest&&highest){if(get().validateIpv4(lowest)&&get().validateIpv4(highest)){if(get().ipToNumber(lowest)>get().ipToNumber(highest)){console.warn('lowest is higher than highest');set({inputRangeValidated:false});return;}
from=lowest;to=highest;set({inputRangeValidated:true});}else if(get().validateIpv6(get().extendIpV6(lowest))&&get().validateIpv6(get().extendIpV6(highest))){if(get().ipToNumber(get().extendIpV6(lowest))>get().ipToNumber(get().extendIpV6(highest))){console.warn('lowest is higher than highest');set({inputRangeValidated:false});return;}
from=get().extendIpV6(lowest);to=get().extendIpV6(highest);set({inputRangeValidated:true});}}
if(get().inputRangeValidated){let lowest=from;let highest=to;set({ipRange:{lowest,highest}});get().fetchCidrData('get_mask_from_range');}},fetchCidrData:async(action)=>{try{const response=await rsssl_api.doAction(action,get().ipRange);if(response){set({cidr:response.cidr,ipAddress:response.cidr,ip_count:response.ip_count,canSetCidr:true});}}catch(e){console.log(e);}},resetRow:async(id,dataActions)=>{set({processing:true});try{const response=await rsssl_api.doAction('delete_entries',{id});if(response&&response.success){await get().fetchData('rsssl_limit_login',dataActions);return{success:true,message:response.message,response};}else{return{success:false,message:response?.message||'Failed to reset ip',response};}}catch(e){console.error(e);return{success:false,message:'Error occurred',error:e};}finally{set({processing:false});}},resetMultiRow:async(ids,dataActions)=>{set({processing:true});try{const response=await rsssl_api.doAction('delete_entries',{ids});if(response&&response.success){if(response.success){await get().fetchData('rsssl_limit_login',dataActions);return{success:true,message:response.message,response};}else
return{success:false,message:response?.message||'Failed to reset ip',response};}}catch(e){console.error(e);return{success:false,message:'Error occurred',error:e};}finally{set({processing:false});}}}));export default IpAddressDataTableStore;