export const estimateTokens=(text)=>{return Math.ceil(text.length / 4);};export const splitIntoSentences=(text)=>{const sentences=text.split(/(?<=[.!?])\s+/).filter(s=>s.length>0);const result=[];for(const sentence of sentences){if(sentence.length>500){const parts=sentence.split(/(?<=[,;])\s+/);result.push(...parts);}else{result.push(sentence);}}
return result;};export const calculateOverlapSentences=(overlapTokens,sentences,currentIndex)=>{let tokens=0;let count=0;for(let i=currentIndex-1;i>=0&&tokens<overlapTokens;i--){tokens+=estimateTokens(sentences[i]);count++;}
return count;};export const generateSimpleTitle=(content,index,fileName)=>{const cleanFileName=fileName.replace(/\.[^/.]+$/,'');const lines=content.split('\n').filter(line=>line.trim().length>0);for(const line of lines.slice(0,5)){const trimmedLine=line.trim();if(trimmedLine.length>10&&trimmedLine.length<100){if(/^(Chapter|Section|Part)\s+\d+/i.test(trimmedLine)||/^\d+\.\s+/.test(trimmedLine)||trimmedLine===trimmedLine.toUpperCase()||trimmedLine.endsWith(':')){if(trimmedLine.length>48){let title=trimmedLine.substring(0,48);title=title.replace(/[.,;:()[\]{}\"'\s]+$/,'');return title.trim()+'...';}
return trimmedLine;}}}
let firstSentence=lines[0]?.substring(0,48)||`${cleanFileName} - Part ${index + 1}`;firstSentence=firstSentence.replace(/\s+/g,' ').trim();if(lines[0]&&lines[0].length>48){firstSentence=firstSentence.replace(/[.,;:()[\]{}\"'\s]+$/,'');firstSentence=firstSentence.trim()+'...';}
return firstSentence;};export const calculatePageRange=(chunkContent,pageTexts)=>{if(!pageTexts||pageTexts.length===0){return'';}
const startSnippet=chunkContent.substring(0,50).trim();for(let i=0;i<pageTexts.length;i++){if(pageTexts[i].includes(startSnippet)){const endSnippet=chunkContent.substring(Math.max(0,chunkContent.length-50)).trim();for(let j=i;j<Math.min(i+3,pageTexts.length);j++){if(pageTexts[j].includes(endSnippet)){return i===j?`Page ${i + 1}`:`Pages ${i + 1}-${j + 1}`;}}
return`Page ${i + 1}`;}}
return'';};export const smartTextChunkingAsync=async(text,pageTexts,density,overlapPercent,fileName,onProgress)=>{const chunks=[];const sentences=splitIntoSentences(text);const chunkSizes={1:2000,2:1000,3:500,4:400,5:200};const maxChunkSize=chunkSizes[density]||500;const overlapTokens=Math.floor(maxChunkSize*(overlapPercent / 100));let currentChunk='';let currentTokens=0;let currentSentences=[];let chunkIndex=0;let sentenceIndex=0;let lastYield=Date.now();let lastChunkEndIndex=0;console.log(`[Client Chunking] Starting with density ${density}, chunk size ${maxChunkSize}, overlap ${overlapPercent}%`);console.log(`[Client Chunking] Processing ${sentences.length} sentences`);while(sentenceIndex<sentences.length){const sentence=sentences[sentenceIndex];const sentenceTokens=estimateTokens(sentence);if(currentTokens+sentenceTokens>maxChunkSize&&currentChunk.length>0){const title=generateSimpleTitle(currentChunk,chunkIndex,fileName);const pageRange=calculatePageRange(currentChunk,pageTexts);chunks.push({title:title,content:currentChunk.trim(),chars:currentChunk.trim().length,tokens:currentTokens,pageRange:pageRange});lastChunkEndIndex=sentenceIndex;const overlapSentenceCount=calculateOverlapSentences(overlapTokens,sentences,sentenceIndex);const overlapStart=Math.max(lastChunkEndIndex-Math.min(overlapSentenceCount,currentSentences.length-1),lastChunkEndIndex-3);currentChunk='';currentTokens=0;currentSentences=[];for(let i=overlapStart;i<lastChunkEndIndex;i++){const overlapSentence=sentences[i];currentChunk+=overlapSentence+' ';currentTokens+=estimateTokens(overlapSentence);currentSentences.push(overlapSentence);}
sentenceIndex=lastChunkEndIndex;chunkIndex++;if(chunkIndex%10===0||Date.now()-lastYield>50){if(onProgress){onProgress(chunkIndex,Math.floor((sentenceIndex / sentences.length)*100));}
console.log(`[Client Chunking] Created ${chunkIndex} chunks...`);await new Promise(resolve=>setTimeout(resolve,0));lastYield=Date.now();}}else{currentChunk+=sentence+' ';currentTokens+=sentenceTokens;currentSentences.push(sentence);sentenceIndex++;}}
if(currentChunk.trim().length>0){const title=generateSimpleTitle(currentChunk,chunkIndex,fileName);const pageRange=calculatePageRange(currentChunk,pageTexts);chunks.push({title:title,content:currentChunk.trim(),chars:currentChunk.trim().length,tokens:currentTokens,pageRange:pageRange});}
console.log(`[Client Chunking] Completed: ${chunks.length} chunks created`);return chunks;};export const smartTextChunking=(text,pageTexts,density,overlapPercent,fileName)=>{console.warn('[Client Chunking] Using synchronous chunking - consider using smartTextChunkingAsync for better performance');const chunks=[];const sentences=splitIntoSentences(text);const chunkSizes={1:2000,2:1000,3:500,4:400,5:200};const maxChunkSize=chunkSizes[density]||500;const overlapTokens=Math.floor(maxChunkSize*(overlapPercent / 100));let currentChunk='';let currentTokens=0;let currentSentences=[];let chunkIndex=0;let sentenceIndex=0;let lastChunkEndIndex=0;console.log(`[Client Chunking] Starting with density ${density}, chunk size ${maxChunkSize}, overlap ${overlapPercent}%`);while(sentenceIndex<sentences.length){const sentence=sentences[sentenceIndex];const sentenceTokens=estimateTokens(sentence);if(currentTokens+sentenceTokens>maxChunkSize&&currentChunk.length>0){const title=generateSimpleTitle(currentChunk,chunkIndex,fileName);const pageRange=calculatePageRange(currentChunk,pageTexts);chunks.push({title:title,content:currentChunk.trim(),chars:currentChunk.trim().length,tokens:currentTokens,pageRange:pageRange});lastChunkEndIndex=sentenceIndex;const overlapSentenceCount=calculateOverlapSentences(overlapTokens,sentences,sentenceIndex);const overlapStart=Math.max(lastChunkEndIndex-Math.min(overlapSentenceCount,currentSentences.length-1),lastChunkEndIndex-3);currentChunk='';currentTokens=0;currentSentences=[];for(let i=overlapStart;i<lastChunkEndIndex;i++){const overlapSentence=sentences[i];currentChunk+=overlapSentence+' ';currentTokens+=estimateTokens(overlapSentence);currentSentences.push(overlapSentence);}
sentenceIndex=lastChunkEndIndex;chunkIndex++;if(chunkIndex%10===0){console.log(`[Client Chunking] Created ${chunkIndex} chunks...`);}}else{currentChunk+=sentence+' ';currentTokens+=sentenceTokens;currentSentences.push(sentence);sentenceIndex++;}}
if(currentChunk.trim().length>0){const title=generateSimpleTitle(currentChunk,chunkIndex,fileName);const pageRange=calculatePageRange(currentChunk,pageTexts);chunks.push({title:title,content:currentChunk.trim(),chars:currentChunk.trim().length,tokens:currentTokens,pageRange:pageRange});}
console.log(`[Client Chunking] Completed: ${chunks.length} chunks created`);return chunks;};export const chapterBasedChunking=(text,pageTexts,detectedHeadings,fileName)=>{const chunks=[];if(!detectedHeadings||detectedHeadings.length===0){console.log('[Client Chunking] No headings detected, falling back to smart chunking');return smartTextChunking(text,pageTexts,3,15,fileName);}
const sortedHeadings=[...detectedHeadings].sort((a,b)=>{if(a.pageIndex!==b.pageIndex){return a.pageIndex-b.pageIndex;}
return a.lineIndex-b.lineIndex;});console.log(`[Client Chunking] Using ${sortedHeadings.length} detected chapters`);const lines=text.split('\n');let currentChunk='';let currentTitle=fileName;let chunkIndex=0;for(let i=0;i<sortedHeadings.length;i++){const heading=sortedHeadings[i];const nextHeading=sortedHeadings[i+1];let startIdx=lines.findIndex(line=>line.includes(heading.text));let endIdx=nextHeading?lines.findIndex(line=>line.includes(nextHeading.text)):lines.length;if(startIdx!==-1){currentChunk=lines.slice(startIdx,endIdx).join('\n');currentTitle=heading.text.substring(0,60);const pageRange=calculatePageRange(currentChunk,pageTexts);chunks.push({title:currentTitle,content:currentChunk.trim(),chars:currentChunk.trim().length,tokens:estimateTokens(currentChunk),pageRange:pageRange});chunkIndex++;}}
console.log(`[Client Chunking] Created ${chunks.length} chapter-based chunks`);return chunks;};