(function(){'use strict';if(window.MwaiChatbot){return;}
const MwaiChatbot={instances:{},loaded:false,loading:false,baseUrl:'',init:async function(config){if(!config.botId){console.error('MwaiChatbot: botId is required');return;}
if(!this.baseUrl){const scripts=document.getElementsByTagName('script');for(let i=0;i<scripts.length;i++){const src=scripts[i].src;if(src&&src.includes('/wp-content/plugins/')&&src.includes('/app/embed.js')){this.baseUrl=src.replace(/\/wp-content\/plugins\/[^\/]+\/app\/embed\.js.*$/,'');break;}}}
if(!this.baseUrl){console.error('MwaiChatbot: Could not determine WordPress site URL');return;}
const instanceId='mwai-'+Date.now()+'-'+Math.random().toString(36).substr(2,9);this.instances[instanceId]={config:config,loaded:false};try{const configUrl=this.baseUrl+'/wp-json/mwai-ui/v1/cross-site/config?botId='+config.botId;const configResponse=await fetch(configUrl,{method:'GET'});if(!configResponse.ok){const error=await configResponse.json();throw new Error(error.message||'Failed to load configuration');}
const configData=await configResponse.json();await this.loadDependencies(configData.pluginUrl);const authData=await this.authenticate(config);const container=this.getContainer(config.container);if(!container){throw new Error('Container element not found');}
container.setAttribute('data-mwai-cross-site','true');container.setAttribute('data-mwai-origin',window.location.origin);this.renderChatbot(instanceId,container,config,authData,configData);}catch(error){console.error('MwaiChatbot initialization failed:',error);this.handleError(instanceId,error.message);}},getContainer:function(container){if(typeof container==='string'){const element=document.querySelector(container);if(!element){alert('AI Engine Cross-Site Error: Container element not found: '+container+'\n\nPlease make sure the container exists on your page or remove the container parameter to use popup mode.');throw new Error('Container element not found: '+container);}
return element;}else if(container instanceof HTMLElement){return container;}else{const div=document.createElement('div');div.className='mwai-chatbot-container mwai-chatbot-popup-container';div.style.position='fixed';div.style.bottom='0';div.style.right='0';div.style.zIndex='9999';document.body.appendChild(div);return div;}},loadDependencies:async function(pluginUrl){if(this.loaded||this.loading){while(this.loading){await new Promise(resolve=>setTimeout(resolve,100));}
return;}
this.loading=true;try{if(!window.React){await this.loadScript('https://unpkg.com/react@18/umd/react.production.min.js');}
if(!window.ReactDOM){await this.loadScript('https://unpkg.com/react-dom@18/umd/react-dom.production.min.js');}
window.React=window.React||window.react;window.ReactDOM=window.ReactDOM||window.reactDOM;window.wp=window.wp||{};const legacyRender=(element,container)=>{if(window.ReactDOM.createRoot){const root=window.ReactDOM.createRoot(container);root.render(element);}else{window.ReactDOM.render(element,container);}};window.wp.element={...window.React,render:legacyRender,createRoot:window.ReactDOM.createRoot,unmountComponentAtNode:window.ReactDOM.unmountComponentAtNode};let chatbotUrl;if(pluginUrl){chatbotUrl=pluginUrl+'app/chatbot.js';}else{const currentScript=document.currentScript||Array.from(document.scripts).find(s=>s.src.includes('/app/embed.js'));if(currentScript&&currentScript.src){chatbotUrl=currentScript.src.replace('/app/embed.js','/app/chatbot.js');}else{console.warn('Could not determine plugin URL, using default path');chatbotUrl=this.baseUrl+'/wp-content/plugins/ai-engine-pro/app/chatbot.js';}}
await this.loadScript(chatbotUrl);this.loaded=true;this.loading=false;}catch(error){this.loading=false;throw error;}},loadScript:function(src){return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=src;script.onload=resolve;script.onerror=()=>reject(new Error('Failed to load script: '+src));document.head.appendChild(script);});},loadStyle:function(href){return new Promise((resolve,reject)=>{const link=document.createElement('link');link.rel='stylesheet';link.href=href;link.onload=resolve;link.onerror=()=>reject(new Error('Failed to load stylesheet: '+href));document.head.appendChild(link);});},authenticate:async function(config){const authUrl=this.baseUrl+'/wp-json/mwai-ui/v1/cross-site/auth';const response=await fetch(authUrl,{method:'POST',headers:{'Content-Type':'application/json',},body:JSON.stringify({botId:config.botId,origin:window.location.origin})});if(!response.ok){const error=await response.json();throw new Error(error.message||'Authentication failed');}
const data=await response.json();return data;},renderChatbot:async function(instanceId,container,config,authData,configData){const instance=this.instances[instanceId];try{const data=configData;if(!data.success){throw new Error(data.message||'Failed to load chatbot configuration');}
if(data.themeCssUrl){await this.loadStyle(data.themeCssUrl);}else if(data.theme&&data.pluginUrl){await this.loadStyle(data.pluginUrl+'themes/'+data.theme+'.css');}
const system={botId:config.botId,customId:null,userData:authData.userData||{},sessionId:authData.sessionId,restNonce:authData.nonce,contextId:null,pluginUrl:data.pluginUrl,restUrl:data.restUrl,stream:data.stream||false,debugMode:false,eventLogs:false,speech_recognition:false,speech_synthesis:false,typewriter:data.typewriter||false,virtual_keyboard_fix:false,crossSite:true,origin:window.location.origin,actions:[],blocks:[],shortcuts:[]};const params=data.params||{};const theme=data.themeData||null;container.className='mwai-chatbot-container';container.setAttribute('data-params',JSON.stringify(params));container.setAttribute('data-system',JSON.stringify(system));container.setAttribute('data-theme',JSON.stringify(theme));container.setAttribute('data-mwai-cross-site','true');if(window.mwaiInitialize){window.mwaiInitialize();}
instance.loaded=true;instance.container=container;if(config.onReady){config.onReady();}}catch(error){console.error('Failed to render chatbot:',error);this.handleError(instanceId,error.message);}},handleError:function(instanceId,message){const instance=this.instances[instanceId];if(instance&&instance.config.onError){instance.config.onError(message);}else{console.error('MwaiChatbot Error:',message);}}};window.MwaiChatbot=MwaiChatbot;document.addEventListener('DOMContentLoaded',function(){const elements=document.querySelectorAll('[data-mwai-chatbot]');elements.forEach(function(element){const config={botId:element.getAttribute('data-mwai-chatbot'),container:element};MwaiChatbot.init(config);});});})();