var Piwik_Overlay_FollowingPages=(function(){var $=jQuery;var followingPages=[];var excludedParams=[];var linksOnPage={};var c;var maxClickRate=0;function load(callback){var location=window.location.href;location=Piwik_Overlay_UrlNormalizer.normalize(location);location=(("https:"==document.location.protocol)?'https':'http')+'://'+location;var excludedParamsLoaded=false;var followingPagesLoaded=false;Matomo_Overlay_Client.api('SitesManager.getExcludedQueryParameters',function(data){for(var i=0;i<data.length;i++){if(typeof data[i]=='object'){data[i]=data[i][0];}}
excludedParams=data;excludedParamsLoaded=true;if(followingPagesLoaded){callback();}});Matomo_Overlay_Client.api('Overlay.getFollowingPages',function(data){followingPages=data;processFollowingPages();followingPagesLoaded=true;if(excludedParamsLoaded){callback();}},'url='+encodeURIComponent(location));}
function processFollowingPages(){var totalClicks=0;for(var i=0;i<followingPages.length;i++){var page=followingPages[i];page.label=Piwik_Overlay_UrlNormalizer.removeUrlPrefix(page.label);totalClicks+=followingPages[i].referrals;}
for(i=0;i<followingPages.length;i++){var clickRate=followingPages[i].referrals / totalClicks*100;followingPages[i].clickRate=clickRate;if(clickRate>maxClickRate)maxClickRate=clickRate;}}
var processLinkDelta=false;function processLink(){var a=$(this);a[0].piwikDiscovered=true;var href=a.attr('href');href=Piwik_Overlay_UrlNormalizer.normalize(href);if(href){if(typeof linksOnPage[href]=='undefined'){linksOnPage[href]=[a];}
else{linksOnPage[href].push(a);}}
if(href&&processLinkDelta!==false){if(typeof processLinkDelta[href]=='undefined'){processLinkDelta[href]=[a];}
else{processLinkDelta[href].push(a);}}}
var repositionTimeout=false;var resizeTimeout=false;function build(callback){$('a').each(processLink);createLinkTags(linksOnPage);positionLinkTags();callback();var repositionAfterTimeout;repositionAfterTimeout=function(){repositionTimeout=window.setTimeout(function(){findNewLinks();positionLinkTags(repositionAfterTimeout);},1800);};repositionAfterTimeout();$(window).resize(function(){if(repositionTimeout){window.clearTimeout(repositionTimeout);}
if(resizeTimeout){window.clearTimeout(resizeTimeout);}
resizeTimeout=window.setTimeout(function(){positionLinkTags();repositionAfterTimeout();},70);});}
function createLinkTags(links){var body=$('body');for(var i=0;i<followingPages.length;i++){var url=followingPages[i].label;if(typeof links[url]!='undefined'){for(var j=0;j<links[url].length;j++){createLinkTag(links[url][j],url,followingPages[i],body);}}}}
function createLinkTag(linkTag,linkUrl,data,body){if(typeof linkTag[0].piwikTagElement!='undefined'&&linkTag[0].piwikTagElement!==null){return;}
linkTag[0].piwikTagElement=true;var rate=data.clickRate;if(rate<0.001){rate='<0.001';}else if(rate<10){rate=Math.round(rate*10)/ 10;}else{rate=Math.round(rate);}
var span=c('span').html(rate+'%');var tagElement=c('div','LinkTag').append(span).hide();tagElement.attr({'data-rateofmax':Math.round(100*rate/maxClickRate)/100});body.prepend(tagElement);linkTag.add(tagElement).hover(function(){highlightLink(linkTag,linkUrl,data);},function(){unHighlightLink(linkTag,linkUrl);});linkTag[0].piwikTagElement=tagElement;}
function positionLinkTags(callback){var url,linkTag,tagElement,offset,top,left,isRight,hasOneChild,inlineChild;var tagWidth=36,tagHeight=21;var tagsToRemove=[];for(var i=0;i<followingPages.length;i++){url=followingPages[i].label;if(typeof linksOnPage[url]!='undefined'){for(var j=0;j<linksOnPage[url].length;j++){linkTag=linksOnPage[url][j];tagElement=linkTag[0].piwikTagElement;if(linkTag.closest('html').length==0||!tagElement){if(tagElement){tagElement.hide();}
tagsToRemove.push({index1:url,index2:j});continue;}
hasOneChild=checkHasOneChild(linkTag);inlineChild=false;if(hasOneChild&&linkTag.css('display')!='block'){inlineChild=linkTag.children().eq(0);}
if(getVisibility(linkTag)=='hidden'||(!linkTag.is(':visible')&&!(hasOneChild&&inlineChild&&inlineChild.is(':visible')))){tagElement.hide();continue;}
tagElement.attr('class','PIS_LinkTag');if(tagElement[0].piwikHighlighted){tagElement.addClass('PIS_Highlighted');}
if(hasOneChild&&linkTag.find('> img').length===1){offset=linkTag.find('> img').offset();if(offset.left==0&&offset.top==0){offset=linkTag.offset();}}else if(inlineChild!==false){offset=inlineChild.offset();}else{offset=linkTag.offset();}
var zoomFactor=1+ +tagElement.attr('data-rateofmax');top=offset.top-tagHeight+6;left=offset.left-tagWidth+10;if(isRight=(left<zoomFactor*tagWidth-tagWidth)){tagElement.addClass('PIS_Right');left=offset.left+linkTag.outerWidth()-10;}
if(top<zoomFactor*tagHeight-tagHeight){tagElement.addClass(isRight?'PIS_BottomRight':'PIS_Bottom');top=offset.top+linkTag.outerHeight()-6;}
tagElement.css({'-webkit-transform':'translate('+left+'px, '+top+'px) scale('+zoomFactor+')','-moz-transform':'translate('+left+'px, '+top+'px) scale('+zoomFactor+')','-ms-transform':'translate('+left+'px, '+top+'px) scale('+zoomFactor+')','-o-transform':'translate('+left+'px, '+top+'px) scale('+zoomFactor+')','transform':'translate('+left+'px, '+top+'px) scale('+zoomFactor+')','opacity':zoomFactor/2});tagElement.show();}}}
for(var k=tagsToRemove.length-1;k>=0;k--){var tagToRemove=tagsToRemove[k];linkTag=linksOnPage[tagToRemove.index1][tagToRemove.index2];if(linkTag&&linkTag[0]&&linkTag[0].piwikTagElement){tagElement=linkTag[0].piwikTagElement;if(tagElement[0].piwikHighlighted){unHighlightLink(linkTag,tagToRemove.index1);}
tagElement.remove();linkTag[0].piwikTagElement=null;}
linksOnPage[tagToRemove.index1].splice(tagToRemove.index2,1);if(linksOnPage[tagToRemove.index1].length==0){delete linksOnPage[tagToRemove.index1];}}
if(typeof callback=='function'){callback();}}
function getVisibility(el){var visibility=el.css('visibility');if(visibility=='inherit'){el=el.parent();if(el.length){return getVisibility(el);}}
return visibility;}
function checkHasOneChild(linkTag){var hasOneChild=(linkTag.children().length===1);if(hasOneChild){var contents=linkTag.contents();if(contents.length>1){contents=contents.filter(function(){return this.nodeType==3&&$.trim(this.data).length>0;});if(contents.length){hasOneChild=false;}}}
return hasOneChild;}
function findNewLinks(){var newLinks=$('a').filter(function(){return typeof this.piwikDiscovered=='undefined'||this.piwikDiscovered===null;});if(!newLinks.length){return;}
processLinkDelta={};newLinks.each(processLink);createLinkTags(processLinkDelta);processLinkDelta=false;}
var highlightElements=[];function highlightLink(linkTag,linkUrl,data){if(highlightElements.length==0){highlightElements.push(c('div','LinkHighlightBoxTop'));highlightElements.push(c('div','LinkHighlightBoxRight'));highlightElements.push(c('div','LinkHighlightBoxLeft'));highlightElements.push(c('div','LinkHighlightBoxText'));var body=$('body');for(var i=0;i<highlightElements.length;i++){body.prepend(highlightElements[i].css({display:'none'}));}}
var width=linkTag.outerWidth();var offset,height;var hasOneChild=checkHasOneChild(linkTag);if(hasOneChild&&linkTag.find('img').length===1){var img=linkTag.find('img');offset=img.offset();height=img.outerHeight();}
if(hasOneChild&&linkTag.css('display')!='block'){var child=linkTag.children().eq(0);offset=child.offset();height=child.outerHeight();width=child.outerWidth();}else{offset=linkTag.offset();height=linkTag.outerHeight();}
var numLinks=linksOnPage[linkUrl].length;putBoxAroundLink(offset,width,height,numLinks,data.referrals);for(var j=0;j<numLinks;j++){var tag=linksOnPage[linkUrl][j][0].piwikTagElement;tag.addClass('PIS_Highlighted');tag[0].piwikHighlighted=true;}
Matomo_Overlay_Client.hideNotifications('LinkLocation');linkTag[0].piwikHideNotification=Matomo_Overlay_Client.notification(Piwik_Overlay_Translations.get('link')+': '+linkUrl,'LinkLocation');}
function putBoxAroundLink(offset,width,height,numLinks,numReferrals){var borderWidth=2;var padding=4;highlightElements[0].width(width+2*padding).css({top:offset.top-borderWidth-padding,left:offset.left-padding}).show();highlightElements[1].height(height+2*borderWidth+2*padding).css({top:offset.top-borderWidth-padding,left:offset.left+width+padding}).show();highlightElements[2].height(height+2*borderWidth+2*padding).css({top:offset.top-borderWidth-padding,left:offset.left-borderWidth-padding}).show();var text;if(numLinks>1){text=Piwik_Overlay_Translations.get('clicksFromXLinks').replace(/%1\$s/,numReferrals).replace(/%2\$s/,numLinks);}else if(numReferrals==1){text=Piwik_Overlay_Translations.get('oneClick');}else{text=Piwik_Overlay_Translations.get('clicks').replace(/%s/,numReferrals);}
var textPadding='&nbsp;&nbsp;&nbsp;';highlightElements[3].html(textPadding+text+textPadding).css({width:'auto',top:offset.top+height+padding,left:offset.left-borderWidth-padding}).show();var minBoxWidth=width+2*borderWidth+2*padding;if(highlightElements[3].width()<minBoxWidth){highlightElements[3].width(minBoxWidth);}}
function unHighlightLink(linkTag,linkUrl){for(var i=0;i<highlightElements.length;i++){highlightElements[i].hide();}
var numLinks=linksOnPage[linkUrl].length;for(var j=0;j<numLinks;j++){var tag=linksOnPage[linkUrl][j][0].piwikTagElement;if(tag){tag.removeClass('PIS_Highlighted');tag[0].piwikHighlighted=false;}}
if((typeof linkTag[0].piwikHideNotification)=='function'){linkTag[0].piwikHideNotification();linkTag[0].piwikHideNotification=null;}}
return{initialize:function(finishCallback){c=Matomo_Overlay_Client.createElement;Matomo_Overlay_Client.loadScript('plugins/Overlay/client/urlnormalizer.js',function(){Piwik_Overlay_UrlNormalizer.initialize();load(function(){Piwik_Overlay_UrlNormalizer.setExcludedParameters(excludedParams);build(function(){finishCallback();})});});},remove:function(){for(var i=0;i<followingPages.length;i++){var url=followingPages[i].label;if(typeof linksOnPage[url]!='undefined'){for(var j=0;j<linksOnPage[url].length;j++){var linkTag=linksOnPage[url][j];var tagElement=linkTag[0].piwikTagElement;if(tagElement){tagElement.remove();}
linkTag[0].piwikTagElement=null;$(linkTag).unbind('mouseenter').unbind('mouseleave');}}}
for(i=0;i<highlightElements.length;i++){highlightElements[i].remove();}
if(repositionTimeout){window.clearTimeout(repositionTimeout);}
if(resizeTimeout){window.clearTimeout(resizeTimeout);}
$(window).unbind('resize');}};})();