import{createRoot}from'@wordpress/element';import BackgroundComponent from'./background-component.js';export const BackgroundControl=wp.customize.MediaControl.extend({renderContent:function renderContent(){let control=this;let root=createRoot(control.container[0]);root.render(<BackgroundComponent control={control}customizer={wp.customize}/>);},initialize:function(id,options){var control=this,args=options||{};args.params=args.params||{};if(!args.params.type){args.params.type='kadence-basic';}
if(!args.params.content){args.params.content=jQuery('<li></li>');args.params.content.attr('id','customize-control-'+id.replace(/]/g,'').replace(/\[/g,'-'));args.params.content.attr('class','customize-control customize-control-'+args.params.type);}
control.propertyElements=[];wp.customize.Control.prototype.initialize.call(control,id,args);},_setUpSettingRootLinks:function(){var control=this,nodes=control.container.find('[data-customize-setting-link]');nodes.each(function(){var node=jQuery(this);wp.customize(node.data('customizeSettingLink'),function(setting){var element=new wp.customize.Element(node);control.elements.push(element);element.sync(setting);element.set(setting());});});},_setUpSettingPropertyLinks:function(){var control=this,nodes;if(!control.setting){return;}
nodes=control.container.find('[data-customize-setting-property-link]');nodes.each(function(){var node=jQuery(this),element,propertyName=node.data('customizeSettingPropertyLink');element=new wp.customize.Element(node);control.propertyElements.push(element);element.set(control.setting()[propertyName]);element.bind(function(newPropertyValue){var newSetting=control.setting();if(newPropertyValue===newSetting[propertyName]){return;}
newSetting=_.clone(newSetting);newSetting[propertyName]=newPropertyValue;control.setting.set(newSetting);});control.setting.bind(function(newValue){if(newValue[propertyName]!==element.get()){element.set(newValue[propertyName]);}});});},ready:function(){var control=this;_.bindAll(control,'openFrame','select');control.container.on('click keydown','.upload-button',function(e){let event=new CustomEvent('kadenceOpenMediaModal',{'detail':false,});document.dispatchEvent(event);control.openFrame(e);});control._setUpSettingRootLinks();control._setUpSettingPropertyLinks();wp.customize.Control.prototype.ready.call(control);control.setting.bind(control.renderContent());control.deferred.embedded.done(function(){});},embed:function(){var control=this,sectionId=control.section();if(!sectionId){return;}
wp.customize.section(sectionId,function(section){if(section.expanded()||wp.customize.settings.autofocus.control===control.id){control.actuallyEmbed();}else{section.expanded.bind(function(expanded){if(expanded){control.actuallyEmbed();}});}});},actuallyEmbed:function(){var control=this;if('resolved'===control.deferred.embedded.state()){return;}
control.renderContent();control.deferred.embedded.resolve();control.container.trigger('init');},focus:function(args){var control=this;control.actuallyEmbed();wp.customize.Control.prototype.focus.call(control,args);},select:function(){var node,attachment=this.frame.state().get('selection').first().toJSON(),device=wp.customize.previewedDevice.get(),settings=this.setting();if(this.id&&this.id==='header_popup_background'){if(device==='tablet'||device==='mobile'){if(undefined!==settings['desktop']&&undefined!==settings['desktop'].type&&settings['desktop'].type==='image'){if(undefined!==settings[device]&&undefined!==settings[device].type&&settings[device].type==='image'){}else{device='desktop';}}}}
if(undefined===this.params.attachment){this.params.attachment={};}
if(undefined===this.params.input_attrs.attachments){this.params.input_attrs.attachments={};}
this.params.input_attrs.attachments[device]=attachment;if(undefined===settings[device]){settings[device]={};}
if(undefined===settings[device].image){settings[device].image={};}
settings[device].image.url=attachment.url;let event=new CustomEvent('kadenceOpenMediaModal',{'detail':true,});document.dispatchEvent(event);this.setting.set({...this.setting.get(),...settings,flag:!this.setting.get().flag});},});